-- AlterTable
ALTER TABLE "products" ALTER COLUMN "ae_price" DROP NOT NULL,
ALTER COLUMN "aed_to_dollar" DROP NOT NULL,
ALTER COLUMN "rate" DROP NOT NULL,
ALTER COLUMN "rating" DROP NOT NULL,
ALTER COLUMN "com_price" DROP NOT NULL,
ALTER COLUMN "shipping_cost" DROP NOT NULL,
ALTER COLUMN "import_fee" DROP NOT NULL,
ALTER COLUMN "total_price" DROP NOT NULL,
ALTER COLUMN "com_rank" DROP NOT NULL;
